// <auto-generated />
namespace GhostLauncher.MasterServer.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class MasterDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MasterDB));
        
        string IMigrationMetadata.Id
        {
            get { return "201411291524203_MasterDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
