//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GhostLauncher.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GhostLauncher.Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add_Label {
            get {
                return ResourceManager.GetString("Add_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel_Label {
            get {
                return ResourceManager.GetString("Cancel_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default_Label {
            get {
                return ResourceManager.GetString("Default_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance folder.
        /// </summary>
        public static string InstanceType_Folder {
            get {
                return ResourceManager.GetString("InstanceType_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single instance.
        /// </summary>
        public static string InstanceType_Path {
            get {
                return ResourceManager.GetString("InstanceType_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add normal instance.
        /// </summary>
        public static string NewInstance_Normal {
            get {
                return ResourceManager.GetString("NewInstance_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add server instance.
        /// </summary>
        public static string NewInstance_Server {
            get {
                return ResourceManager.GetString("NewInstance_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok_Label {
            get {
                return ResourceManager.GetString("Ok_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove_Label {
            get {
                return ResourceManager.GetString("Remove_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart application.
        /// </summary>
        public static string Restart_Label {
            get {
                return ResourceManager.GetString("Restart_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance locations.
        /// </summary>
        public static string Settings_InstanceLocations_Title {
            get {
                return ResourceManager.GetString("Settings_InstanceLocations_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string Settings_Menu_Main {
            get {
                return ResourceManager.GetString("Settings_Menu_Main", resourceCulture);
            }
        }
    }
}
